#!/usr/bin/env bash

VERSION="1.0"

## Use Docksal on not local environment.
##
## This is an notlocal addon. It's purpose is to show sample folder structure
## and concepts of creating addons.
##
##   fin notlocal <command>
##
## Usage:
##   up       Start the system stack
##   version  Display addon version

# Abort if anything fails
set -e
#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red() { echo -e "${red}$1${NC}"; }
echo-green() { echo -e "${green}$1${NC}"; }
echo-green-bg() { echo -e "${green_bg}$1${NC}"; }
echo-yellow() { echo -e "${yellow}$1${NC}"; }

#-------------------------- END: Helper functions --------------------------------

case "$1" in
up)
  $ADDON_ROOT/commands/start
  ;;
version | -v)
  echo "$VERSION"
  ;;
*)
  fin help notlocal
  ;;
esac
