#!/usr/bin/env bash

VERSION="1.0"

## Use Docksal on not local environment.
##
## This is an notlocal addon. TODO
##
##   fin notlocal <command>
##
## Usage:
##   up       Start the system stack
##   version  Display addon version

# Abort if anything fails
set -e
#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red() { echo -e "${red}$1${NC}"; }
echo-green() { echo -e "${green}$1${NC}"; }
echo-green-bg() { echo -e "${green_bg}$1${NC}"; }
echo-yellow() { echo -e "${yellow}$1${NC}"; }

#-------------------------- END: Helper functions --------------------------------
command=""
if [ ! -z $1 ]; then
  command=$1
  shift
fi

commands_available=$(find $ADDON_ROOT/commands -type f -printf "%f ")
commands_available=${commands_available%" "}

case "$command" in
version | -v)
  echo "$VERSION"
  ;;
"" | help)
  fin help notlocal
  ;;
*)
  if printf '%s\n' ${commands_available[@]} | grep -q -P "^$command$"; then
    $ADDON_ROOT/commands/$command "$@"
  else
    echo-yellow "Command $command not found."
    fin help notlocal
  fi
  ;;
esac
