#!/usr/bin/env bash

VERSION="1.0"

## Use Docksal on not local environment.
##
## This is an notlocal addon. TODO
##
##   fin notlocal <command>
##
## Usage:
##      start	                Start the system stack
##      stop	                Stop system stack
##      reset	                Reset system stack
##      status	                Get system stack status
##      logs	                Get system stack logs
##      dc	                docker-compose
##      htpasswd                Generate http passwords
##      update-basic-auth       Update http basic authentication info
##      version                 Display addon version

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------
source $ADDON_ROOT/inc/common.inc
#-------------------------- END: Helper functions --------------------------------

command=""
if [ ! -z $1 ]; then
  command=$1
  shift
fi

commands_available=$(find $ADDON_ROOT/commands -type f -printf "%f ")
commands_available=${commands_available%" "}

case "$command" in
version | -v)
  echo "$VERSION"
  ;;
"" | help)
  fin help notlocal
  ;;
status)
  fin notlocal dc ps
  ;;
start)
  fin notlocal dc up -d
  ;;
stop)
  fin notlocal dc rm
  ;;
reset)
  fin notlocal stop
  fin notlocal start
  ;;
*)
  if printf '%s\n' ${commands_available[@]} | grep -q -P "^$command$"; then
    $ADDON_ROOT/commands/$command "$@"
  else
    echo-yellow "Command $command not found."
    fin help notlocal
  fi
  ;;
esac
