#!/usr/bin/env bash

## Initialize a Docksal powered DKAN 7.x site
##
## Usage: fin notlocal dc

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------
source $ADDON_ROOT/inc/common.inc
#-------------------------- END: Helper functions --------------------------------

notlocal_acme_email=$(fin config get NOTLOCAL_ACME_EMAIL --global)

if [ -z "${notlocal_acme_email}" ]; then
  echo-red "Empty NOTLOCAL_ACME_EMAIL global variable! Please update global docksal.env"
  exit 1
fi

fin dc -p system -f "$ADDON_ROOT/stacks/system/notlocal.yml" $@
