#!/usr/bin/env bash

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red() { echo -e "${red}$1${NC}"; }
echo-green() { echo -e "${green}$1${NC}"; }
echo-green-bg() { echo -e "${green_bg}$1${NC}"; }
echo-yellow() { echo -e "${yellow}$1${NC}"; }

die() {
  echo-red $1
  exit 1
}
#-------------------------- END: Helper functions --------------------------------

# Generate user:password pair suitable for
# traefik.frontend.auth.basic.users=EXPR as described in
# https://docs.traefik.io/configuration/backends/docker/#docker
echo $(fin docker run --rm -ti xmartlabs/htpasswd $@)
