#!/usr/bin/env bash

#-------------------------- Helper functions --------------------------------
source $ADDON_ROOT/inc/common.inc
#-------------------------- END: Helper functions --------------------------------

# Generate user:password pair suitable for
# traefik.frontend.auth.basic.users=EXPR as described in
# https://docs.traefik.io/configuration/backends/docker/#docker
echo $(fin docker run --rm -ti xmartlabs/htpasswd $@)
