#!/usr/bin/env bash

## Initialize a Docksal powered DKAN 7.x site
##
## Usage: fin init

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red() { echo -e "${red}$1${NC}"; }
echo-green() { echo -e "${green}$1${NC}"; }
echo-green-bg() { echo -e "${green_bg}$1${NC}"; }
echo-yellow() { echo -e "${yellow}$1${NC}"; }

die() { echo-red $1; exit 1; }
#-------------------------- END: Helper functions --------------------------------

# Abort if anything fails
set -e

[ ! -z "$SSL_EMAIL" ] || die "Empty SSL_EMAIL global variable"

fin dc -p system -f "$ADDON_ROOT/stacks/system/notlocal.yml" up -d
